"""Add occupation column to User

Revision ID: b653e2bfc2b2
Revises: 5e8c5aba335c
Create Date: 2024-10-13 23:16:39.773804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b653e2bfc2b2'
down_revision = '5e8c5aba335c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mental_health_input', schema=None) as batch_op:
        batch_op.alter_column('systolic',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=7),
               existing_nullable=False)
        batch_op.alter_column('diastolic',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=7),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('occupation')

    with op.batch_alter_table('mental_health_input', schema=None) as batch_op:
        batch_op.alter_column('diastolic',
               existing_type=sa.Float(precision=7),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('systolic',
               existing_type=sa.Float(precision=7),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
